### ISSUE TITLE
TooManyRequestsException - Again..

### ISSUE THREAD

**Issue by robbelroot** [jorgerosal/amazon-paapi#16]
Hey guys i'm having the same issue as described here:
https://github.com/jorgerosal/amazon-paapi/issues/8

Sure i did change the Marketplace to my requirements = 'www.amazon.de'

I also did some research where i read, that amazon seems to balance those requests (throttling) partially based on your sales.

I just want to search by API for listed products and their prices (by keyword).

And i'm getting this crappy (sorry) error, already with my first and only request.

Has anybody an idea?

I mean how am i supposed to do anything with that kind of problem, this totally burns my development.

Best regards, Rob.

**Comment by polilluminato** [comment]
Same here, in my [previous comment](https://github.com/jorgerosal/amazon-paapi/issues/8#issuecomment-884367291) I said that with that package.json the problem automagically disappears... now magically it has reappeared. 
I have a bot for Telegram and now unfortunately I have to stop it again 😔

**Comment by polilluminato** [comment]
I think I have found the explanation as to why this thing happens, which also answers #8. As said in these discussions: 

- [The request was denied due to request throttling](https://github.com/nager/Nager.AmazonProductAdvertising/issues/146)
- [PA API v5: Requests throttled even with a single request through Scratchpad](https://forums.aws.amazon.com/thread.jspa?threadID=311773)
- [TooManyRequestsException with Amazon Product Advertising API](https://stackoverflow.com/questions/62809583/toomanyrequestsexception-with-amazon-product-advertising-api)

> As of January, 2019 – Amazon has now placed restrictions and limitations on who gets access to the API. Basically, you MUST have qualified sales attributed to API links within the previous trailing 30 days in order to prevent your API access from being revoked or limited (throttled).

> If you aren't making enough sales in every 30 day period the access to the PA-API system will be revoked without notice.

> If you don't made any sales (with the PA PI link type) you loose the access to the api. After you make revenue gain you again will earn request based on the revenue. Understandable so far. However there is no explanation how to solve this. Because the problem is, if you can't request the api you can't make revenue with this link type.

So, maybe, you need to shop through your custom link if you want to keep API access for your account alive.

**Comment by robbelroot** [comment]
@polilluminato Thanks for your time and effort, this is what i likely feared being the problem.. I read about this but well, they gotta be kidding...
